### ISSUE TITLE
Err: no passcode found

### ISSUE THREAD

**Issue by Namelio** [r2dev2/OneFactorAuth#1]
i'm on linux 
i tried to connect on a account with 2fa with a https://receivesms.cc/sms/ 
but i dont receive the passcode 
and the terminal say :
Err: no passcode found
how can i fix that?

**Comment by r2dev2** [comment]
Recently, some authentication tools like Duo (at least for UCLA login) have stopped sending passcodes to receivesms. You can check the actual receivesms url to see if its truly being sent or not.

If you are able to find a different free online number service that Duo still sends codes to, please let me know! I would love to add support for a different service that works with Duo.

**Comment by Namelio** [comment]
hi, I think my problem is not that it's that I can't connect to bypass 2fa 
and it marks me number of error no passcode found
and i don't know how i can fix that
